# Generated by Django 5.0.4 on 2024-04-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling', '0003_remove_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.service')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity_gb', models.IntegerField()),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('speed_mbps', models.IntegerField()),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpu_cores', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.tarif')),
            ],
        ),
    ]
