# Generated by Django 5.0.4 on 2024-04-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling', '0004_tarif_storage_network_virtualmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.service')),
            ],
        ),
        migrations.AlterField(
            model_name='network',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.tariff'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.tariff'),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='tariff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biling.tariff'),
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
    ]
