# Generated by Django 5.0.4 on 2024-04-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biling', '0005_tariff_alter_network_tariff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='tariff_id',
            new_name='network_tariff_id',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='tariff_id',
            new_name='storage_tariff_id',
        ),
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='tariff_id',
            new_name='virtual_machine_tariff_id',
        ),
    ]
