# Generated by Django 5.0.4 on 2024-04-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biling', '0007_rename_service_id_tariff_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network_tariff_id',
            new_name='network_tariff',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='storage_tariff_id',
            new_name='storage_tariff',
        ),
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='virtual_machine_tariff_id',
            new_name='virtual_machine_tariff',
        ),
    ]
