# Generated by Django 5.0.4 on 2024-05-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biling', '0008_rename_network_tariff_id_network_network_tariff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='data_center',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='service_tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biling.tariff'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='data_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biling.datacenter'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
